[[main]]
  identifier = "about"
  name = "Sobre"
  url = "about"
  weight = 1

[[main]]
  identifier = "archive"
  name = "Arquivo"
  url = "archive"
  weight = 2

[[main]]
  identifier = "gallery"
  name = "Galeria"
  url = "gallery"
  weight = 3
    
[[main]]
  parent = "gallery"
  name = "Cartoon"
  url = "gallery/cartoon"

[[main]]
  parent = "gallery"
  name = "Foto"
  url = "gallery/photo"

[[main]]
  identifier = "posts"
  name = "Posts"
  url = "posts"
  weight = 4
    
[[main]]
  identifier = "notes"
  name = "notas"
  url = "notes"
  weight = 5